# -----------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
spec: 
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: frontendaman8765.azurecr.io/frontend:44
        imagePullPolicy: Always
        env:
          - name: VITE_API_URL
            value: "https://app.nilssonsstadtjanst.se" # If SSL is configured keep https other http is fine
        ports:
        - containerPort: 5173